version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:12.4 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  web:
    image: sergrampro/yamdb_final:latest
    # build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
    env_file:
      - ./.env


  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/code/static
      - media_volume:/code/media
    links:
      - web
    ports:
      - 80:80
    depends_on:
      - web